apiVersion: v1
kind: Service
namespace: {{ .Values.namespaceOverride }}
metadata:
  name: opentelemetry-collector-prometheus
spec:
  selector:
    app: opentelemetry-collector
  ports:
    - name: prometheus
      port: {{ .Values.ports.prometheus }}
      targetPort: prometheus
