apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.namespaceOverride}}
  name: grafana
  annotations:
    metallb.io/loadBalancerIPs: {{ .Values.service.loadBalancerIP }}
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
    - name: grafana
      port: {{ .Values.service.port }}
      targetPort: grafana