image:
  repository: "prom/prometheus"
  tag: latest

namespaceOverride: "prometheus"

service:
  loadBalancerIP: 192.168.18.102
  port: 9090

persistence:
  size: 1Gi
  storageClass: local-path

config:
  global:
    scrape_interval: 15s
  scrape_configs:
    - job_name: 'otel-collector'
      static_configs:
        - targets: ['opentelemetry-collector-prometheus.opentelemetry:9464'] 