apiVersion: v1
kind: Service
namespace: {{ .Values.namespaceOverride }}
metadata:
  name: prometheus
  annotations:
    metallb.io/loadBalancerIPs: {{ .Values.service.loadBalancerIP }}
spec:
  type: LoadBalancer
  selector:
    app: prometheus
  ports:
    - name: prometheus
      port: {{ .Values.service.port }}
      targetPort: prometheus